spring.datasource.url=jdbc:mysql://localhost:3306/crypto_db?useSSL=false
spring.datasource.username=your_username
spring.datasource.password=your_password

mybatis.configuration.map-underscore-to-camel-case=true

binance.api.kline-url=https://www.binance.com/api/v1/klines?symbol=%s&interval=1m&startTime=%d&endTime=%d&limit=%d